### ISSUE TITLE
Configurar el tamaño de las imágenes de los acordes

### ISSUE THREAD

**Issue by jpegazo** [FUSAKLA/gdocs-songbook#1]
Amigo,

Al agregar las imágenes de los acordes, se agregan con un tamaño pequeño y debo y agrandando uno a uno. 

¿es posible que puedas agregar la función de seleccionar el tamaño que se agregará al documento?

¿se entiende?

Muchas gracias por tu desarrollo, me sirvió mucho.

**Comment by FUSAKLA** [comment]
Hola,

Agregué la opción de establecer el tamaño del diagrama de acordes como un porcentaje. ¿Puedes probar si te funciona bien? Debería ser liberado.

![image](https://user-images.githubusercontent.com/6112562/196553512-f3c3ed35-4168-41ae-92b0-309130b4902f.png)


Gracias de antemano por comprobar.

(lo siento, estoy usando un traductor, solo sé checo e inglés)

**Comment by jpegazo** [comment]
¡Muchas gracias!

¡Funciona perfectamente!
