### ISSUE TITLE
QR Code Upload Throwing Error

### ISSUE THREAD

**Issue by djsevans87** [FUSAKLA/gdocs-songbook#2]
![Screen Shot 2023-02-12 at 14 56 01](https://user-images.githubusercontent.com/125184994/218303069-691c2e5a-cb23-4f78-b097-111d1dde72a6.png)

**Comment by FUSAKLA** [comment]
Ups.. thanks for reporting.
I'll take a look at it if I find a the time.

**Comment by FUSAKLA** [comment]
Hi @djsevans87 sorry for the delay.
May I ask how you add the QR code? Was it during import of a song from any website, or you entered the link to be generated by hand using this dialog?
![image](https://user-images.githubusercontent.com/6112562/222932507-683855d6-8265-41fe-818d-2ae9429321d9.png)

In the first case, could you please provide a link to the song that caused it?

In the second case, please, could you provide the URL you tried to get a QR code for?

Thanks for reporting!

**Comment by djsevans87** [comment]
I don't recall exactly now. I think it was an ultimateguitar tab url.

**Comment by FUSAKLA** [comment]
Sorry, I'm afraid I won't be able to fix this without more detailed info how to reproduce the error.

If it happens again, please feel free to reopen the issue and add more details.

Thanks!
