### ISSUE TITLE
Having problems importing songs from https://lacuerda.net/

### ISSUE THREAD

**Issue by JoseRPerez** [FUSAKLA/gdocs-songbook#3]
Hello, 
I'm having problems importing songs from https://lacuerda.net/. If you can fix it I will be very grateful to you.
Thank you

**Comment by FUSAKLA** [comment]
Hi! Yes that is sadly true because I never herd of this site till now, so it wasn't supported.

But if it would help you, I can take a look how hard would it be to support it :)

Hopefully I'll find a while soon

**Comment by juampolo** [comment]
Hi @FUSAKLA ! I would love to use Lacuerda.net too.... Is the #1 Chord base for Spanish Speakers and spanish songs!

Thanks in advance for sharing your work!

**Comment by FUSAKLA** [comment]
Ok, I see there is bigger demand for it.
Still can't finde the time, but will try more :)

**Comment by FUSAKLA** [comment]
Just released new version which supports the https://lacuerda.net so please @juampolo @JoseRPerez, give it a try.
I tried several songs and versions of the chords and seems to be working fine so :crossed_fingers: 

In case of any issues, please feel free to reopen the issue :)

Happy playing! :)
