### ISSUE TITLE
No Ukulele F chord

### ISSUE THREAD

**Issue by palmerstan** [FUSAKLA/gdocs-songbook#4]
I am not seeing a basic F chord in the Ukulele chord diagrams.
![image](https://github.com/FUSAKLA/gdocs-songbook/assets/143910963/c6977f0f-c215-420f-891e-c499e9520573)

**Comment by FUSAKLA** [comment]
Hi, hm that is unfortunate thanks for reporting, and sorry for such late reply :confounded: 

I just added it, so hopefully you will see it now 

https://github.com/FUSAKLA/gdocs-songbook/blob/master/docs/assets/chords/ukulele/F.png

**Comment by palmerstan** [comment]
Thank you! I love the extension! 

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 25, 2023 at 18:35, Martin ***@***.***> wrote:   


Hi, hm that is unfortunate thanks for reporting, and sorry for such late reply 😖

I just added it, so hopefully you will see it now

https://github.com/FUSAKLA/gdocs-songbook/blob/master/docs/assets/chords/ukulele/F.png

**Comment by FUSAKLA** [comment]
I'm glad to hear that! :)
