### ISSUE TITLE
Suggestion to add a new source of Chords and Tabs

### ISSUE THREAD

**Issue by jdmasa** [FUSAKLA/gdocs-songbook#5]
Dear sirs,

I would like you to consider adding the website https://www.songbook.fun/ to your list of compatible Import places.

This is my main source of chords, the one that I am using to learn how to play ukelele.

Thank you.

**Comment by FUSAKLA** [comment]
Hi! Even though the site is not particularly big, I don't have many requests to add some other sites, so I can definitely take a look at it and if it won't be a big issue, add the support for it.

I'll reply here once I find a free while how it went.

**Comment by FUSAKLA** [comment]
So! I finally found a while and the support for importing from https://songbook.fun should be there :tada: 

If you don't mind @jdmasa trying it out, I'd be happy to hear if it works for you :)
