### ISSUE TITLE
Add support for transposing slash chords

### ISSUE THREAD

**Issue by joshfermin** [FUSAKLA/gdocs-songbook#6]
Currently when I try to transpose a slash chord i.e. `D/F#` it wont transpose the F# bass note

**Comment by FUSAKLA** [comment]
Hi, thanks for reporting!

 I do fear that might not be properly handled :confused: 
I'll try to take a look at it once I Find a free while.

**Comment by FUSAKLA** [comment]
Ok, I believe this should be fixed now.
Could you @joshfermin please verify? :pray:

**Comment by joshfermin** [comment]
@FUSAKLA that works great! thank you

**Comment by FUSAKLA** [comment]
Great! Thanks for confirmation :)
