### ISSUE TITLE
Chords website from Brazil

### ISSUE THREAD

**Issue by anviqs** [FUSAKLA/gdocs-songbook#7]
Hi, first of all, I would like to thank you for the wonderful extension that you´ve created, it has been very helpful.. I would like to know if its possible to add https://www.cifraclub.com.br/ to the website catalog as it is the largest chord charts website here in Brazil. Thank you for your attention.

**Comment by FUSAKLA** [comment]
Hi! Thank you for all the kind words :) 

Not 100% sure but I suppose it should be fairly easy, I'll try :+1:

**Comment by FUSAKLA** [comment]
Ok, it was trivial, will release new version supporting it today

**Comment by FUSAKLA** [comment]
Deployed new version, please try it out, I tried just few songs and reopen this issue or open new one if you bump into any issues
